#### Author: Aditya Nambiar
### Create a Private S3 Bucket - Simplest script ###

## Note:
### "!Sub" = Substitute a Global variable in the value you are defining.

Resources:
  BucketFromVSCode:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}
      AccessControl: Private  # Keep a practise to never create a Public S3 bucket
      VersioningConfiguration:  # S3 FileSystem requires Bucket to be Version Enabled.
        Status: Enabled

Outputs: 
  BucketFromVSCode:
    Value: !Ref BucketFromVSCode
    Description: Logical ID of S3 bucket 
    Export: 
      Name: BucketFromVSCode
  BucketFromVSCodeArn:
    Value: !GetAtt BucketFromVSCode.Arn
    Description: ARN of S3 bucket 
    Export: 
      Name: BucketFromVSCodeArn