#### Author: Aditya Nambiar
### Create an EC2 instance with 20GB Hard disk attached (Block Store) & Keypair ###
### Instance must also have access to Internet ###


# Requirements
# AMI ID: "ami-0f559c3642608c138"
# Default BlockDeviceMapping : "/dev/xvda"
# BlockDeviceMapping - Ebs:
#     - /dev/trimdiceapp
#     - VolumeType: "io1"
#     - VolumeSize: 20
#     - DeleteOnTermination: true

## Note:
### "!Ref" = Refer another resource 

Resources:
    TrimDiceKeyPair:
        Type: AWS::EC2::KeyPair
        Properties:
            KeyName: !Sub trim_dice_keypair-${AWS::StackName}
    TrimDiceInstance:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: "ami-0f559c3642608c138"
            InstanceType: "t2.micro"
            KeyName: !Ref TrimDiceKeyPair
            BlockDeviceMappings:
            - DeviceName: "/dev/sdt"
              Ebs:
                VolumeType: "io1"
                Iops: 200
                VolumeSize: 20
                DeleteOnTermination: true
            NetworkInterfaces:
            - AssociatePublicIpAddress: "true"   ## As of Mar 2026, Public address can only be assigned via CloudFormation script if DeviceIndex = 0 & we are creating a new Network interface (VPC and PublicSubnet) 
              DeviceIndex: "0"
              GroupSet: 
              - Ref: TrimDicePublicSG
              SubnetId:
                Ref: TrimDicePublicSubnet
            Tags:   
            - Key: Name
              Value: TrimDiceInstance

      
